### ISSUE TITLE
`lumen -V` getting wrong version

### ISSUE THREAD

**Issue by jmattaa** [jnsahaj/lumen#34]
I've realised after installing version 1.6.0 with homebrew that running `lumen -V` would result in saying `lumen 1.5.0`. I've run into a similar issue before, I've resolved it by forcing an update to the source code of the tag by doing a:
```
git tag -f v1.6.0
git push origin -f v1.6.0
```
This creates new compressed files at the tag so the sha will need to be updated.

**Comment by jnsahaj** [comment]
I believe this must be an issue with the way I built the homebrew release
Since the version is decided at the compile-time using `clap`, the `Cargo.toml` must be updated before creating the release build that goes into homebrew

Thanks for the issue - I'll change the release build over at `homebrew-lumen`
