### ISSUE TITLE
Large git diffs result in no output

### ISSUE THREAD

**Issue by wouterschiedam** [jnsahaj/lumen#4]
Description

When attempting to summarize large diffs, the lumen library fails to provide an output. This issue primarily affects diffs that exceed a certain size, which seems to prevent the summarization from completing successfully.

Example

Here is an example from one of my personal repositories ([chess-engine](https://github.com/wouterschiedam/chess-engine)):

Commit with a large diff:
	•	Commit Hash: bd34eda9ad9e61916193f66e4c15f0f993749078

https://github.com/wouterschiedam/chess-engine/commit/bd34eda9ad9e61916193f66e4c15f0f993749078
	
Steps to Reproduce

`lumen list`
`Commit : init magics`

Output: 

`✓ Done`

**Comment by jnsahaj** [comment]
Update on this: the free AI model "phind" returns a "null" response for large input sizes.

I have since added error handling to show that a response was not produced.

I can't technically say that the input was too large since the API doesn't tell me the reason for a "null" response.

Let me know if you have any suggestions, or I'll mark this closed
